version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: tag_autocomplete
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:password@db:5432/tag_autocomplete
      DB_ECHO: "false"
      LOG_LEVEL: info
      AUTO_IMPORT_CSV: "true"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  llama-server:
    image: ghcr.io/ggml-org/llama.cpp:full-cuda
    ports:
      - "8080:8080"
    volumes:
      - ./models:/models
    shm_size: 8g
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: >
      --server
      -m /models/Qwen3-0.6B.Q6_K.gguf
      -c 32768
      -ngl 28
      --port 8080
      --host 0.0.0.0
      --threads 16
      --temp 0.6
      --top-p 0.95
      --top-k 20
      --repeat-penalty 1.1
      --batch-size 4096
      --ubatch-size 1024
      --n-predict 32768
      --parallel 8
      --cont-batching
      --flash-attn
      --mlock
      --verbose
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  postgres_data: